steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-app']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-app'
      - '--image=asia-south1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-app'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--vpc-connector=my-vpc-connector'
      - '--add-cloudsql-instances=testing-practice-org:asia-south1:my-sql-instance'
      - '--set-env-vars=DB_USER=demo-user,DB_PASS=demo-pass,DB_NAME=demo-db,INSTANCE_CONNECTION_NAME=testing-practice-org:asia-south1:my-sql-instance'
      - '--allow-unauthenticated'
